const root=document.documentElement;
const loader=document.querySelector('.loader');
window.addEventListener('load',()=>setTimeout(()=>loader?.classList.add('done'),650));
const cursor=document.querySelector('.cursor');
window.addEventListener('pointermove',e=>{if(cursor){cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'}});
const bindHot=()=>document.querySelectorAll('a,button,.panel,.project-card,.next-card').forEach(el=>{el.addEventListener('mouseenter',()=>cursor?.classList.add('hot'));el.addEventListener('mouseleave',()=>cursor?.classList.remove('hot'))});bindHot();
const saved=localStorage.getItem('interlinked-theme');if(saved&&['signal','relic'].includes(saved))root.dataset.theme=saved;
function syncTheme(){document.querySelectorAll('[data-theme-btn]').forEach(b=>b.classList.toggle('active',b.dataset.themeBtn===root.dataset.theme))}syncTheme();
document.querySelectorAll('[data-theme-btn]').forEach(btn=>btn.addEventListener('click',()=>{root.dataset.theme=btn.dataset.themeBtn;localStorage.setItem('interlinked-theme',btn.dataset.themeBtn);syncTheme()}));
const menu=document.querySelector('.site-menu'),trigger=document.querySelector('.menu-trigger');trigger?.addEventListener('click',()=>menu?.classList.toggle('open'));document.querySelectorAll('.menu-links a').forEach(a=>a.addEventListener('click',()=>menu?.classList.remove('open')));document.addEventListener('keydown',e=>{if(e.key==='Escape')menu?.classList.remove('open')});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
window.addEventListener('scroll',()=>document.querySelectorAll('[data-parallax]').forEach(el=>{const r=el.getBoundingClientRect();const f=parseFloat(el.dataset.parallax||0);el.style.transform=`translate3d(0,${(innerHeight/2-r.top)*f}px,0)`}),{passive:true});
const wrap=document.querySelector('.track-wrap'),track=document.querySelector('.track');if(wrap&&track){let tx=0,drag=false,startX=0,startTx=0;const clamp=()=>Math.max(-(track.scrollWidth-wrap.clientWidth),Math.min(0,tx));const render=()=>{tx=clamp();track.style.transform=`translate3d(${tx}px,0,0)`};wrap.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)>=Math.abs(e.deltaX)){e.preventDefault();tx-=e.deltaY*.85}else tx-=e.deltaX;render()},{passive:false});wrap.addEventListener('pointerdown',e=>{drag=true;startX=e.clientX;startTx=tx;wrap.setPointerCapture(e.pointerId)});wrap.addEventListener('pointermove',e=>{if(!drag)return;tx=startTx+(e.clientX-startX);render()});wrap.addEventListener('pointerup',()=>drag=false);wrap.addEventListener('pointercancel',()=>drag=false)}
const tabs=document.querySelectorAll('[data-state]');tabs.forEach(btn=>btn.addEventListener('click',()=>{tabs.forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('.state-layer').forEach(l=>l.classList.toggle('active',l.dataset.layer===btn.dataset.state))}));
